const DATA_SOURCES=["data/jinju_weather.csv","data/busan_weather.csv"];
const weatherGrid=document.querySelector("#weather-grid"),historyGrid=document.querySelector("#history-grid"),updateSummary=document.querySelector("#update-summary"),refreshButton=document.querySelector("#refresh-button");
const WEATHER_CODES=[{codes:[0],label:"맑음",icon:"☀️"},{codes:[1,2],label:"대체로 맑음",icon:"🌤️"},{codes:[3],label:"흐림",icon:"☁️"},{codes:[45,48],label:"안개",icon:"🌫️"},{codes:[51,53,55,56,57],label:"이슬비",icon:"🌦️"},{codes:[61,63,65,66,67,80,81,82],label:"비",icon:"🌧️"},{codes:[71,73,75,77,85,86],label:"눈",icon:"🌨️"},{codes:[95,96,99],label:"뇌우",icon:"⛈️"}];
function parseCSV(text){const rows=text.trim().split(/\r?\n/).filter(Boolean);if(rows.length<2)throw new Error("관측 데이터가 없습니다.");const headers=rows[0].split(",");return rows.slice(1).map(row=>Object.fromEntries(row.split(",").map((value,index)=>[headers[index],value])))}
function getWeather(code){return WEATHER_CODES.find(item=>item.codes.includes(Number(code)))??{label:"날씨 정보",icon:"🌡️"}}
function formatObservation(value,includeDate=false){return new Intl.DateTimeFormat("ko-KR",{...(includeDate?{month:"short",day:"numeric"}:{}),hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value))}
function renderWeatherCard(record){const fragment=document.querySelector("#weather-card-template").content.cloneNode(true),weather=getWeather(record.weather_code);fragment.querySelector(".location").textContent=record.location;fragment.querySelector(".weather-icon").textContent=weather.icon;fragment.querySelector(".temperature").textContent=`${Number(record.temperature_c).toFixed(1)}°`;fragment.querySelector(".condition").textContent=weather.label;fragment.querySelector(".observed-time").textContent=`${formatObservation(record.observed_at)} 관측`;fragment.querySelector(".feels-like").textContent=`${Number(record.apparent_temperature_c).toFixed(1)}°`;fragment.querySelector(".humidity").textContent=`${record.relative_humidity_pct}%`;fragment.querySelector(".precipitation").textContent=`${Number(record.precipitation_mm).toFixed(1)} mm`;return fragment}
function renderHistory(location,records){const panel=document.createElement("article"),title=document.createElement("h3");panel.className="history-panel";title.textContent=location;panel.append(title);records.slice(-2).reverse().forEach(record=>{const row=document.createElement("div");row.className="history-row";row.innerHTML=`<time datetime="${record.observed_at}">${formatObservation(record.observed_at,true)}</time><div class="history-stat"><span>기온</span><strong>${Number(record.temperature_c).toFixed(1)}°</strong></div><div class="history-stat"><span>체감</span><strong>${Number(record.apparent_temperature_c).toFixed(1)}°</strong></div><div class="history-stat"><span>습도</span><strong>${record.relative_humidity_pct}%</strong></div>`;panel.append(row)});return panel}
async function loadWeather(){refreshButton.disabled=true;refreshButton.classList.add("is-spinning");updateSummary.textContent="최신 데이터를 확인하고 있어요.";try{const datasets=await Promise.all(DATA_SOURCES.map(async path=>{const response=await fetch(`${path}?v=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`${path} 파일을 읽지 못했습니다.`);return parseCSV(await response.text())}));weatherGrid.replaceChildren();historyGrid.replaceChildren();datasets.forEach(records=>{const latest=records.at(-1);weatherGrid.append(renderWeatherCard(latest));historyGrid.append(renderHistory(latest.location,records))});const latestTime=datasets.map(records=>records.at(-1).observed_at).sort().at(-1);updateSummary.textContent=`${formatObservation(latestTime,true)} 기준 업데이트`}catch(error){weatherGrid.innerHTML=`<div class="error-panel"><strong>날씨를 불러오지 못했어요.</strong><p>${error.message}</p><small>로컬에서는 웹 서버를 통해 index.html을 열어주세요.</small></div>`;historyGrid.replaceChildren();updateSummary.textContent="데이터 연결을 확인해 주세요."}finally{refreshButton.disabled=false;refreshButton.classList.remove("is-spinning")}}
function renderToday(){const now=new Date();document.querySelector("#today-day").textContent=new Intl.DateTimeFormat("ko-KR",{weekday:"short"}).format(now);document.querySelector("#today-date").textContent=new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric"}).format(now)}
refreshButton.addEventListener("click",loadWeather);renderToday();loadWeather();
